### ISSUE TITLE
not gated behind research

### ISSUE THREAD

**Issue by drdozer** [nicolas-lang/Factorio.SpaceShuttle#1]
I have k2, se and some other mods installed including aircraft and space shuttle. When you start a new game, with no techs unlocked, the space shuttle recipe is enabled already. I was expecting it to be gated behind something in the post-nauvis tech tree. It's not a game-breaker, but I just thought it was odd.

**Comment by nicolas-lang** [comment]
I agree.
When I first created the mod I was already mid-game and didn't really care. It has a implicit gate though, as it requires the cargo plane as ingredient.

I'll look into it, it shouldn't be complex.

Might take a while as it's not my top1 priority atm though.

**Comment by drdozer** [comment]
Cheers :) I think just making a tech with a dependency on cargo planes tech and astrometrics I would do it

**Comment by nicolas-lang** [comment]
fixed
