### ISSUE TITLE
Crash with Aircraft mod version 1.8.2

### ISSUE THREAD

**Issue by robot256** [nicolas-lang/Factorio.SpaceShuttle#2]
Latest version of Aircraft mod changed icon sizes to 64 pixels.  Space Shuttle icon size is 32 pixels.  This causes a crash when starting the game.  Safest thing to do is add `entity.icon_size = 32` and `item.icon_size = 32` to `data_final_fixes.lua`.  If you change the icon to 64 pixels, update those lines, but keep them so that any further changes in Aircraft don't affect your icons.

Full error message:
```
Mods to disable:Failed to load mods: The given sprite rectangle (left_top=0x0, right_bottom=64x64) is outside the actual sprite size (left_top=0x0, right_bottom=32x32).
If this is being used as an icon you may need to define the icon_size property.
See the log file for more information.: __nco-SpaceShuttle__/graphics/se-space-shuttle_icon.png

Mods to be disabled:
• nco-SpaceShuttle (0.0.2)
```

**Comment by nicolas-lang** [comment]
duplicate/similiar to #4

**Comment by robot256** [comment]
You're right, it's all for the same graphics update. This one was game breaking and that one wasn't, so I thought to separate them, but not really needed.
