### ISSUE TITLE
Incompatibility with Aircraft Realism mod

### ISSUE THREAD

**Issue by robot256** [nicolas-lang/Factorio.SpaceShuttle#3]
Loading Space Shuttle and Aircraft Realism at the same time results in the game crashing whenever you try to drive a Space Shuttle.  This is because Aircraft Realism thinks it is a "grounded" plane, and cannot find the airspeed settings associated with se-space-shuttle.

In `data-final-fixes`, Aircraft Realism changes the item-prototype `order` property for the specific planes that it supports.  However, Space Shuttle 0.0.2 copies the `cargo-plane` prototype in `data-final-fixes`, _after_ Aircraft Realism makes this change (because non-dependent mods are processed alphabetically).

The solution is to change `data-final-fixes` to `data-updates`.  This ensures that Space Shuttle copies the `cargo-plane` prototype before Aircraft Realism makes any changes to it.

For reference, there is an unofficial convention for how to use "data", "data-updates", and "data-final-fixes" to minimize issues like this:

> data.lua - Add new items/entities.
> data-updates.lua - Modify another mod's new items/entities, or create derivative items/entities based on mods  in your dependency list.
> data-final-fixes.lua - Modify parameters of existing prototypes, don't make new ones unless absolutely necessary.

See this post for a bit more discussion on the topic: https://forums.factorio.com/viewtopic.php?p=330341#p330341

**Comment by nicolas-lang** [comment]
thanks for the detailed description, I'll look into this.

**Comment by nicolas-lang** [comment]
fixed
