### ISSUE TITLE
Space Shuttle graphics not applied with Aircraft version 1.8.2

### ISSUE THREAD

**Issue by robot256** [nicolas-lang/Factorio.SpaceShuttle#4]
The latest Aircraft update applied a new structure to the animation prototypes, that does not work with the Space Shuttle sprite sheets.  You can copy the animation structure from an older version of the Aircraft mod and overwrite it so that your sprite sheets work again.  Or get in touch with snouz (who redid the Aircraft graphics) and see if they wants to make a custom model for Space Shuttle!

**Comment by nicolas-lang** [comment]
Hi, I was already planning to reach out to snouz since I really like his work on the models...
I'll probably look into a quick--fix this weekend and try to get snouz involved for a hr model afterwards...

**Comment by nicolas-lang** [comment]
I have created a hotfixed version, but I don't have much time for testing. I would appreciate if you could have a look if this beta fixes your issues.

[nco-SpaceShuttle_0.0.2.zip](https://github.com/nicolas-lang/Factorio.SpaceShuttle/files/7530851/nco-SpaceShuttle_0.0.2.zip)

(the hotfix covers all currently known issues)

**Comment by robot256** [comment]
Yes, looks like that works!  Graphics look good, and Aircraft Realism leaves it alone.

There's a separate bug I'm tracking down, SE isn't enabling it after being teleported in a spaceship.  But I'm not sure which mod needs to fix that yet.  Edit: Found it, and it's definitely in SE.

**Comment by nicolas-lang** [comment]
I don't think I would want to bother the SE team with that.
The space-shuttle is living at the very edge of "this is not intended to work this way" and I don't want them to look to much into that... I'll clean up the commits later and push a update for the existing issues later and I  would be happy if you just opened a new issue for the cloning issue.

P.S. for me Aircraft Realism does not add a hud to the shuttle...

**Comment by robot256** [comment]
They've already fixed it--was an obvious typo. I didn't mention space shuttle. 😉

**Comment by snouz** [comment]
Hi Nicolas! I just noticed your mod (when looking after Aircraft, it didn't come up)

I'm copying your repo and maybe apply some optimizations if you're ok with that! (previous messages imply that you are :) )

**Comment by nicolas-lang** [comment]
Hi snouz,
**I am!**
... I like to see every bit of improvement this gets.
Also I really liked your up-scaled models, I would probably have reached to you, trying to get you involved for a new sprite-sheet, I just wanted to clean up my mess a bit first ;-)

P.S. I didn't really like the way the engine-smoke looked in space since it seemed to much like it was "drifting" in an atmosphere, for now I am just killing it since this was the most simple thing to do.

**Comment by nicolas-lang** [comment]
fixed
