### ISSUE TITLE
Sprite-sheet improvements and code optimizations

### ISSUE THREAD

**Issue by nicolas-lang** [nicolas-lang/Factorio.SpaceShuttle#5]
@snouz lets continue our discussion here (or in discord), since I was about to close the other issue.

**Comment by robot256** [comment]
I'll also mention that Vehicle Wagon 2 supports custom graphics for loaded vehicles, if you are interested.  YuokiTani made ones for the Cargo Plane, Gunship, and Jet.  You could make a wagon spritesheet for the shuttle on a flat car.  We can add it to Vehicle Wagon 2, or maybe come up with an interface so other mods can add wagon sprites for their vehicles.

**Comment by snouz** [comment]
https://github.com/nicolas-lang/Factorio.SpaceShuttle/pull/7

**Comment by nicolas-lang** [comment]
update 0.0.4 based on #7 released
