### ISSUE TITLE
Suggestion: Remove dependency on Aircraft

### ISSUE THREAD

**Issue by robot256** [nicolas-lang/Factorio.SpaceShuttle#6]
It could be useful to remove the dependency on Aircraft for users who only want the Shuttle.  It should be easy since you use your own graphics (unless I'm forgetting something).  You would do this by copying the rest of the prototype data that is set for the cargo-plane into your mod, and adding an alternative recipe like you did with/without Krastorio.

I suppose you could make an alternative recipe for when Space Exploration is not installed, but that seems like a small use case.

**Comment by robot256** [comment]
Just realized you use the sounds too. I might look for some spacey sounds, but feel free to close this.

**Comment by nicolas-lang** [comment]
there are two reasons why i did it this way:
- simpler code
- with the current implementation aircraft gets also credit if someone installs this mod.

...I wouldn't mind adding nicer space sounds though.
